<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Contacts</name>
   <tag></tag>
   <elementGuidId>9f18a1a0-ddc3-4571-a50d-de19fb922a93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-sidebar-pusher']/div/div/div/span[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>15734ec1-20ee-470d-bd77-4ae1f2925811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>640a1ef2-c879-4163-ae9d-e70e1d440104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>88d02942-2508-4ef9-bbcf-f3d7d92a1f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>68130a8f-3eaf-48cc-bdc6-c74357c5681e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ffa8baf0-51e7-418a-96c2-1846528fb780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contacts</value>
      <webElementGuid>6fb42a65-74be-4516-bff9-866ed76d3dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-sidebar-pusher&quot;)/div[@class=&quot;post-login&quot;]/div[@class=&quot;postlogin-container&quot;]/div[@class=&quot;ui postlogin menu&quot;]/span[@class=&quot;menu-item-dropdown item menuItem
      SubMenu_root__3gO3W&quot;]/div[@class=&quot;ui active visible dropdown menu-item-dropdown&quot;]/div[@class=&quot;text&quot;]</value>
      <webElementGuid>fbb74665-6621-41f8-949d-7ede16b142df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-sidebar-pusher']/div/div/div/span[2]/div/div</value>
      <webElementGuid>11130d22-4c13-43a9-a375-8fb7791c6039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inbox'])[1]/following::div[2]</value>
      <webElementGuid>3f3e738f-5777-49c0-8ed5-9cad65f07697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[2]/preceding::div[1]</value>
      <webElementGuid>3023ff48-503e-4b51-82df-7eee09fb3d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lists'])[1]/preceding::div[2]</value>
      <webElementGuid>6e29e71c-ec39-4051-91c3-7746109913c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contacts']/parent::*</value>
      <webElementGuid>7f804ea6-cc4b-42b0-bd32-de9c9b05b84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/div</value>
      <webElementGuid>0d8dc84a-3558-42a8-9eca-37e54531ea9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Contacts' or . = 'Contacts')]</value>
      <webElementGuid>83aee7db-8f7b-4dc0-b6b5-58f5d1ba37d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
