<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>5c8b6e86-c56c-4065-a31e-6dab4bc3c63f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.c5cafd14f > button[name=&quot;action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='action'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fafc054-fe6a-45e2-bf71-2096f3877655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>81dc0779-fe5c-4d2b-96fb-1e815ae7844e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>25897821-58ec-4760-9d07-ca10ee56820e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>ca1b366c-06bc-41d9-aa86-530df08910d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c3768468a cd7c8bf9c c4a5884bf c127814b1 c8f6f5254</value>
      <webElementGuid>22d3eff2-7ffa-4cf3-b153-03e1ffbbd144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-button-primary</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f517ef2-7eed-4583-9c61-696d628a1c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>cb3d3ff7-f5e0-4cd9-b3a9-c49278d984c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;prompt-wrapper section&quot;]/main[@class=&quot;_widget login&quot;]/section[@class=&quot;c22d42f7e _prompt-box-outer ce1ecc585&quot;]/div[@class=&quot;c63580e18 cc29cdfb1&quot;]/div[@class=&quot;c1f4727c4&quot;]/div[@class=&quot;c7bd5e6dd cb6ef9106&quot;]/form[@class=&quot;c5b634b9f c96c0661e&quot;]/div[@class=&quot;c5cafd14f&quot;]/button[@class=&quot;c3768468a cd7c8bf9c c4a5884bf c127814b1 c8f6f5254&quot;]</value>
      <webElementGuid>87c4dd4f-1f15-4428-a523-242ff33bc4d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='action'])[2]</value>
      <webElementGuid>f86490ac-7aaf-451f-87c4-8134ba722370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/main/section/div/div/div/form/div[3]/button</value>
      <webElementGuid>bb6bd92a-60ee-4dd3-996d-0f2ba20c8dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::button[1]</value>
      <webElementGuid>50bf2cef-7e19-47e2-b851-c43f1f867d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide password'])[2]/following::button[1]</value>
      <webElementGuid>30bb7c56-e274-48c6-94f4-96db46a8e964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::button[1]</value>
      <webElementGuid>b2edb02c-153d-45e2-a04a-4afe54217322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::button[1]</value>
      <webElementGuid>116f2dec-2f8d-4111-8bf2-1ac63a24027c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>7cd6c34b-f25c-42e2-a8c5-1dc822063455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>b695a0ac-8d6c-40a3-a0c5-d4f2ebc27db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
