<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b2505445-3a86-44c9-8e13-49e9197e8c84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;MALAYSIA&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='MALAYSIA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>03df7c09-ab34-4807-bbf6-f810835e9f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.maybank2u.com.my/iwov-resources/images/malaysia-icon.png</value>
      <webElementGuid>7a48aa28-ac27-49a3-a41a-0ab48b8915e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MALAYSIA</value>
      <webElementGuid>fb5f3fe0-aec9-47ed-95e8-9c022cbdb4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[4]/div[@class=&quot;fade CountryModal---container---3TMws in modal&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/ul[@class=&quot;CountryModal---listCountry---3s6tB&quot;]/li[@class=&quot;CountryModal---active---3B79R&quot;]/a[1]/img[1]</value>
      <webElementGuid>45c6c813-4f19-42a0-b255-e6d9f789de5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='MALAYSIA']</value>
      <webElementGuid>c6f0c82b-52d6-41d8-a264-0036c582fb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/img</value>
      <webElementGuid>0983e1df-7052-4027-9582-178d8813a624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.maybank2u.com.my/iwov-resources/images/malaysia-icon.png' and @alt = 'MALAYSIA']</value>
      <webElementGuid>6f4b87f9-fb44-44b7-b089-dea4e92c0524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
