<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_MALAYSIA</name>
   <tag></tag>
   <elementGuidId>bdae9617-5e52-4456-a8e6-a00f1d49ec2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.CountryModal---active---3B79R</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Country'])[1]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5add2b22-5771-468e-b75c-b081c26cf56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CountryModal---active---3B79R</value>
      <webElementGuid>ae43a954-8bf7-4f73-b362-f94adedb7daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MALAYSIA</value>
      <webElementGuid>d1d68bd0-4f83-43a2-8ef9-17ef1c9e6c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[4]/div[@class=&quot;fade CountryModal---container---3TMws in modal&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/ul[@class=&quot;CountryModal---listCountry---3s6tB&quot;]/li[@class=&quot;CountryModal---active---3B79R&quot;]</value>
      <webElementGuid>ba80b3c8-c8f9-4b3e-a161-f1ef8f85e8ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Country'])[1]/following::li[1]</value>
      <webElementGuid>31cb4433-be1d-4e61-b5d1-e93c702ddd9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best viewed on the latest versions of Chrome, Firefox, Edge, Safari.'])[1]/following::li[18]</value>
      <webElementGuid>d61bdc94-1b84-4c80-940b-181c2cf0a6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INDONESIA'])[1]/preceding::li[1]</value>
      <webElementGuid>40f0db6a-34f0-4354-849f-518e0ed30dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/ul/li</value>
      <webElementGuid>fdaa5dfd-6a7a-48f9-84b2-2353fd3995fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'MALAYSIA' or . = 'MALAYSIA')]</value>
      <webElementGuid>ee1e36cc-4950-4173-b113-e60c147c8ab9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
