<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MALAYSIA</name>
   <tag></tag>
   <elementGuidId>10d99dd7-f8e8-4268-8c5f-88dcaad620c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choose-country > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='choose-country']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7573873e-e627-49f1-8771-051a70eebde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MALAYSIA</value>
      <webElementGuid>09ee8de3-1efe-4204-9838-c6c1a9db109d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choose-country&quot;)/span[1]</value>
      <webElementGuid>149fb2fb-e363-45e9-bd7b-614a08888c5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='choose-country']/span</value>
      <webElementGuid>0e71dbe0-e728-4ccb-9329-a81b8b6a8dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAYBANK ISLAMIC'])[1]/following::span[1]</value>
      <webElementGuid>68978a12-39ec-4ed1-93a3-1bf830ac788e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAYBANK PRIVATE'])[2]/following::span[2]</value>
      <webElementGuid>0739ef0b-37de-4aa3-b86f-be47f96ab481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'choose-country', '&quot;', ')/span[1]')])[1]/preceding::span[1]</value>
      <webElementGuid>6b61718e-1b5c-4155-8e6a-c8732d37490e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MALAYSIA']/parent::*</value>
      <webElementGuid>a06d6d09-41bc-46f9-8562-f5d620f7ed14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>69f7f314-7f32-4843-835b-c24160faec50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MALAYSIA' or . = 'MALAYSIA')]</value>
      <webElementGuid>4d4c568d-c315-432a-9b92-c27b8a4c280f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
