<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Date of birth__5dbc _5k_6 img sp_98fCI7IV_fcf079</name>
   <tag></tag>
   <elementGuidId>cfb6789f-f211-471c-8aaf-9ce27c4192fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i._5dbc._5k_6.img.sp_98fCI7IVTTz.sx_54513f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='birthday_wrapper']/div[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3448284c-aa8f-4cdb-baf3-4ed1e0291b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_5dbc _5k_6 img sp_98fCI7IVTTz sx_54513f</value>
      <webElementGuid>098330da-469c-4a55-8d69-5c2a237e7a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthday_wrapper&quot;)/div[@class=&quot;_5k_5&quot;]/i[@class=&quot;_5dbc _5k_6 img sp_98fCI7IVTTz sx_54513f&quot;]</value>
      <webElementGuid>4c8d113d-6196-4003-8a2c-981c6fb35296</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='birthday_wrapper']/div[2]/i</value>
      <webElementGuid>d11efaf9-ae31-4f88-b476-93e5827f28e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>3f618703-e1c8-42fe-a971-d20a9b9fda4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
